import json
from datetime import datetime

# Load the saved data
with open('btc_market_data.json') as f:
    data = json.load(f)

# The data is stored as strings, need to parse
for tf in data:
    data[tf] = json.loads(data[tf])

# Helper to extract stats
def extract_tf_stats(tf, tf_data):
    btc_data = tf_data.get('BTC-USDT', {})
    if isinstance(btc_data, dict) and 'data' in btc_data:
        bars = btc_data['data']
    elif isinstance(btc_data, list):
        bars = btc_data
    else:
        return None
    
    if not bars:
        return None
    
    latest = bars[-1]
    first = bars[0]
    
    change_pct = (latest['close'] - first['open']) / first['open'] * 100
    
    # Calculate some basic stats
    highs = [b['high'] for b in bars]
    lows = [b['low'] for b in bars]
    volumes = [b['volume'] for b in bars]
    
    return {
        'bars': len(bars),
        'current': latest['close'],
        'open': first['open'],
        'change_pct': change_pct,
        'high': max(highs),
        'low': min(lows),
        'avg_volume': sum(volumes) / len(volumes),
        'last_volume': latest['volume'],
        'trend': 'UP' if change_pct > 0 else 'DOWN' if change_pct < 0 else 'FLAT'
    }

# Parse all timeframes
stats = {}
for tf in ['5m', '15m', '1h', '4h']:
    tf_data = data[tf]
    stats[tf] = extract_tf_stats(tf, tf_data)

# Build evidence package
lines = []
lines.append('# Evidence Package: BTC-USDT M5 Scalping')
lines.append('')
lines.append('## Metadata')
lines.append('- **Symbol:** BTC-USDT')
lines.append('- **Primary Timeframe:** M5')
lines.append('- **Secondary Timeframes:** M15, H1, H4')
lines.append(f'- **Timestamp:** {datetime.now().isoformat()}')
lines.append('- **Data Sources:** get_market_data (OKX auto)')
if stats.get('5m'):
    lines.append(f'- **Current Price:** ${stats["5m"]["current"]:,.2f}')
lines.append('')

# Market Data Summary Table
lines.append('## Market Data Summary (per TF)')
lines.append('| TF | Bars | Range | Current | vs Open | Trend |')
lines.append('|----|------|-------|---------|---------|-------|')
for tf in ['5m', '15m', '1h', '4h']:
    s = stats.get(tf)
    if s:
        range_pts = s['high'] - s['low']
        lines.append(f'| {tf.upper()} | {s["bars"]} | {s["high"] - s["low"]:,.0f} | ${s["current"]:,.2f} | {s["change_pct"]:+.2f}% | {s["trend"]} |')
lines.append('')

# Key Levels from M5
if stats.get('5m'):
    s5 = stats['5m']
    lines.append('## Key Levels (from M5)')
    lines.append('| Level | Price | Source |')
    lines.append('|-------|-------|--------|')
    lines.append(f'| Resistance | ${s5["high"]:,.2f} | M5 recent high |')
    lines.append(f'| Support | ${s5["low"]:,.2f} | M5 recent low |')
    lines.append(f'| Current | ${s5["current"]:,.2f} | Latest close |')
    lines.append('')

# Volume info
if stats.get('5m'):
    s5 = stats['5m']
    lines.append('## Volume / Flow (M5)')
    vol_trend = "Increasing" if s5["last_volume"] > s5["avg_volume"] else "Decreasing"
    vol_ratio = s5["last_volume"] / s5["avg_volume"]
    lines.append(f'- **M5 Volume Trend:** {vol_trend}')
    lines.append(f'- **Volume vs Avg:** {vol_ratio:.2f}x avg')
    lines.append(f'- **Last Bar Volume:** {s5["last_volume"]:.4f}')
    lines.append('')

# News & Catalysts
lines.append('## News & Catalysts')
lines.append('| Source | Headline | Impact | Time |')
lines.append('|--------|----------|--------|------|')
lines.append('| Web | Bitcoin false breakout of resistance in bear market — BINANCE:BTCUSDT.P forming retest of key 64,500 resistance | Bearish | Recent |')
lines.append('| Web | Bitcoin needs stronger institutional demand or macro catalyst to sustain move above $65K | Neutral | 3 days ago |')
lines.append('| Web | Bear case: rejection at 50-day EMA and upper Bollinger Band near $65,300–$65,457 | Bearish | 1 week ago |')
lines.append('')

# Macro (not available)
lines.append('## Macro Context')
lines.append('- DXY: Not available (FRED_API_KEY not configured)')
lines.append('- 10Y Yield: Not available (FRED_API_KEY not configured)')
lines.append('- Session: Weekend / Asian open')
lines.append('')

# Scalp Readiness
lines.append('## Scalp Readiness Assessment')
if stats.get('5m') and stats.get('1h'):
    s5 = stats['5m']
    s1h = stats['1h']
    alignment = 'ALIGNED' if (s5['trend'] == stats['1h']['trend']) else 'CONFLICT'
    lines.append(f'- **Trend Alignment (M5/H1):** {alignment}')
lines.append(f'- **Liquidity Session:** Weekend / Asian open (thin)')
lines.append(f'- **Spread Expectation:** WIDE (weekend)')
lines.append(f'- **Catalyst Risk:** MEDIUM (no major scheduled events)')
lines.append('')

lines.append('---')
lines.append(f'*Generated by scalp-evidence-builder v0.1 at {datetime.now().isoformat()}*')

evidence = '\n'.join(lines)

# Save
with open('Evidence_BTC-USDT_M5_001.md', 'w') as f:
    f.write(evidence)

print('Evidence saved to Evidence_BTC-USDT_M5_001.md')
print()
# Print the evidence
with open('Evidence_BTC-USDT_M5_001.md') as f:
    print(f.read())